# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
   - command: npm install -g serverless
   - command: npm install -g https://github.com/softprops/serverless-rust
  
# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
